title: NerfLearning
description: >-
  A self-guided Swift and SwiftUI curriculum for an experienced programmer,
  using NerfJournal as the working example throughout.

remote_theme: just-the-docs/just-the-docs@v0.10.0

url: https://nerfjournal.rjbs.cloud
logo: /assets/images/icon.png

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

color_scheme: light

# Footer
footer_content: "this content generated for <a href='https://rjbs.cloud/'>rjbs</a> and of questionable value to anybody else"
