title: NerfJournal
description: >-
  A self-guided Swift and SwiftUI curriculum for an experienced programmer,
  using NerfJournal as the working example throughout.

remote_theme: just-the-docs/just-the-docs@v0.10.0

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

color_scheme: light

# Footer
footer_content: "this content generated for rjbs and of questionable value to anybody else"
